spring.datasource.url=jdbc:postgresql://arrochadb.cjbxbv36ynlz.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=universidade
spring.datasource.username=joseantonio
spring.datasource.password={bute a senha aqui e tire as chaves}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.port=8081